name: local
variables:
  - name: baseUrl
    value: http://localhost:1234
    type: default
  - name: actorName
    value: "Test User"
    type: default
  - name: actorEmail
    value: test@example.com
    type: default
  - name: projectName
    value: "My Review"
    type: default
